name: Push Accent Translations

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install -g accent-cli
      - run: accent sync --add-translations --merge-type=passive
        env:
          ACCENT_API_KEY: ${{ secrets.ACCENT_API_KEY }}