name: Sync Accent Translations

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install -g accent-cli
      - run: accent sync --add-translations --merge-type=passive --order-by=key
        env:
          ACCENT_API_KEY: ${{ secrets.ACCENT_API_KEY }}
      - uses: peter-evans/create-pull-request@v4
        with:
          add-paths: "public/locales/**/*.json"
          commit-message: Update Accent
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: accent
          draft: false
          delete-branch: true
          title: New translations are available to merge
          body: Translation files have been updated, feel free to merge this pull request after review.
